import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { signIn, signOut, useSession } from 'next-auth/react';
import Card from '@components/Card';
import useGreeting from '@lib/greetings/useGreeting';

const Home: NextPage = () => {
  const { status, data } = useSession();
  const { data: greeting } = useGreeting({
    name: data?.user?.email || '',
  });
  return (
    <div className="min-h-screen flex flex-col justify-between dark:bg-black dark:text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-16 px-0 flex flex-col justify-center items-center">
        <h1 className="m-0 text-6xl text-center text-blue-400">
          {greeting ? greeting.greeting : 'Hello'}
        </h1>

        <p className="text-center my-16 text-2xl">
          Get started by editing{' '}
          <code className="bg-slate-200 dark:bg-slate-800 rounded p-3 text-lg ">
            pages/index.tsx
          </code>
        </p>

        {status === 'unauthenticated' && (
          <button onClick={() => signIn()}>Sign in</button>
        )}
        {status === 'authenticated' && (
          <button onClick={() => signOut()}>Sign out</button>
        )}

        <div className="flex flex-wrap align-center justify-center w-full flex-column md:max-w-[800px] md:flex-row">
          <Card
            title="Documentation &rarr;"
            text="Find in-depth information about Next.js features and API."
            link="https://nextjs.org/docs"
          />

          <Card
            title="Learn &rarr;"
            text="Learn about Next.js in an interactive course with quizzes!"
            link="https://nextjs.org/learn"
          />

          <Card
            title="Examples &rarr;"
            text="Discover and deploy boilerplate example Next.js projects"
            link="https://github.com/vercel/next.js/tree/canary/examples"
          />

          <Card
            title="Deploy &rarr;"
            text="Instantly deploy your Next.js site to a public URL with Vercel."
            link="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          />
        </div>
      </main>

      <footer className="py-8 flex justify-center align-center border-t border-solid border-slate-300 dark:border-gray-900">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center align-center"
        >
          Powered by{' '}
          <span className="h-4 ml-2 dark:invert">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
