#!/bin/sh
# Builds the NextJS application using `next build`, with additional setup
# steps for Prisma.
#
# If running under the production environment on Vercel, this script also
# applies any pending database migrations using Prisma.

set -e

prisma generate

if [ "$VERCEL_ENV" = "production" ]; then
  echo "Running $VERCEL_ENV migrations for prisma"
  prisma migrate deploy
fi

exec next build

